/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package face_rec;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author HOME
 */
public class Attendance extends javax.swing.JFrame {

DB db =new DB();
    /**
     * Creates new form Attendance
     */
    public Attendance() {
        this.setTitle("Attendance Process");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        initComponents();
        showtable();
        showtable1();
        showtable3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Student = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StuDate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSID = new javax.swing.JTextField();
        StuID = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        StuRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStu = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Pai_Stu = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Stu_Att = new javax.swing.JButton();
        Staff = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        StaDate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtStaID = new javax.swing.JTextField();
        StaID = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        StuRefresh1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        PaiSat = new javax.swing.JButton();
        SatBack = new javax.swing.JButton();
        StaAtt = new javax.swing.JButton();
        StaAtt1 = new javax.swing.JButton();
        StaAtt2 = new javax.swing.JButton();
        Unknown = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        untbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        StaDate1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtStaID1 = new javax.swing.JTextField();
        StaID1 = new javax.swing.JButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        StuRefresh2 = new javax.swing.JButton();
        SatBack1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setText("SELECT DATE");

        StuDate.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        StuDate.setText("SEARCH");
        StuDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuDateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setText("ENTER STUDENT ID");

        txtSID.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        StuID.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        StuID.setText("SEARCH");
        StuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuIDActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");

        StuRefresh.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        StuRefresh.setText("Refresh");
        StuRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StuDate)
                            .addComponent(StuID)))
                    .addComponent(StuRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StuID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StuDate))
                .addGap(9, 9, 9)
                .addComponent(StuRefresh))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblStu.setBorder(new javax.swing.border.MatteBorder(null));
        tblStu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        Pai_Stu.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Pai_Stu.setText("Pie Chart");
        Pai_Stu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        Pai_Stu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pai_StuActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Stu_Att.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Stu_Att.setText("Attendance Process");
        Stu_Att.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        Stu_Att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stu_AttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Stu_Att, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pai_Stu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pai_Stu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stu_Att, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout StudentLayout = new javax.swing.GroupLayout(Student);
        Student.setLayout(StudentLayout);
        StudentLayout.setHorizontalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        StudentLayout.setVerticalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student Attendance", Student);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setText("SELECT DATE");

        StaDate.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        StaDate.setText("SEARCH");
        StaDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaDateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setText("ENTER STAFF ID");

        txtStaID.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        StaID.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        StaID.setText("SEARCH");
        StaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaIDActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        jLabel7.setIconTextGap(0);

        StuRefresh1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        StuRefresh1.setText("Refresh");
        StuRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuRefresh1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStaID)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StaID)
                            .addComponent(StaDate)))
                    .addComponent(StuRefresh1))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StaID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(StaDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StuRefresh1)
                .addGap(3, 3, 3))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblStaff.setBorder(new javax.swing.border.MatteBorder(null));
        tblStaff.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStaffMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblStaff);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        jPanel8.setLayout(null);

        PaiSat.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        PaiSat.setText("Pie Chart");
        PaiSat.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        PaiSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaiSatActionPerformed(evt);
            }
        });
        jPanel8.add(PaiSat);
        PaiSat.setBounds(390, 60, 161, 39);

        SatBack.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        SatBack.setText("Back");
        SatBack.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        SatBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatBackActionPerformed(evt);
            }
        });
        jPanel8.add(SatBack);
        SatBack.setBounds(40, 60, 131, 39);

        StaAtt.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        StaAtt.setText("Attendance Process");
        StaAtt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        StaAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaAttActionPerformed(evt);
            }
        });
        jPanel8.add(StaAtt);
        StaAtt.setBounds(90, 10, 220, 39);

        StaAtt1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        StaAtt1.setText("Monthly Salary");
        StaAtt1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        StaAtt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaAtt1ActionPerformed(evt);
            }
        });
        jPanel8.add(StaAtt1);
        StaAtt1.setBounds(180, 60, 200, 39);

        StaAtt2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        StaAtt2.setText("OFF");
        StaAtt2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        StaAtt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaAtt2ActionPerformed(evt);
            }
        });
        jPanel8.add(StaAtt2);
        StaAtt2.setBounds(320, 10, 153, 39);

        javax.swing.GroupLayout StaffLayout = new javax.swing.GroupLayout(Staff);
        Staff.setLayout(StaffLayout);
        StaffLayout.setHorizontalGroup(
            StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        StaffLayout.setVerticalGroup(
            StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Staff Attendance", Staff);

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Image");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        untbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        untbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                untblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(untbl);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setText("Unauthorized Person Details");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel8.setText("SELECT DATE");

        StaDate1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        StaDate1.setText("SEARCH");
        StaDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaDate1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel9.setText("ENTER TIME");

        txtStaID1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        StaID1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        StaID1.setText("SEARCH");
        StaID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaID1ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/un.png"))); // NOI18N
        jLabel10.setIconTextGap(0);

        StuRefresh2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        StuRefresh2.setText("Refresh");
        StuRefresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuRefresh2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(StuRefresh2))
                            .addComponent(jLabel9))
                        .addGap(240, 240, 240))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStaID1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StaID1)
                    .addComponent(StaDate1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StaID1)
                        .addComponent(txtStaID1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StaDate1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StuRefresh2)
                .addGap(8, 8, 8))
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        SatBack1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        SatBack1.setText("Back");
        SatBack1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        SatBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UnknownLayout = new javax.swing.GroupLayout(Unknown);
        Unknown.setLayout(UnknownLayout);
        UnknownLayout.setHorizontalGroup(
            UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UnknownLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(UnknownLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(UnknownLayout.createSequentialGroup()
                .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UnknownLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UnknownLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(SatBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UnknownLayout.setVerticalGroup(
            UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnknownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SatBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Unknown Person Entry", Unknown);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Staff Attendence");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StuDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuDateActionPerformed
       try {
           
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(jDateChooser1.getDate());
            if (date.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Enter Attendance Date !!!");
                return;
            }

            PreparedStatement pst = db.getpst("SELECT SID,Date,Time,Status FROM stuattendance WHERE Date='" + date + "'");
            ResultSet rs = pst.executeQuery();
            tblStu.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_StuDateActionPerformed

    private void StuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuIDActionPerformed
       try {
            String sid = txtSID.getText();
            if (sid.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Enter Student Id !!!");
                return;
            }

            PreparedStatement pst = db.getpst("SELECT SID,Date,Time,Status FROM stuattendance WHERE SID='" + txtSID.getText() + "'");
            ResultSet rs = pst.executeQuery();
            tblStu.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_StuIDActionPerformed

    private void StaDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaDateActionPerformed
       try {
           
              
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(jDateChooser2.getDate());
            if (date.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Enter Attendance Date !!!");
                return;
            }

            PreparedStatement pst = db.getpst("SELECT EID,Date,InTime,OutTime,Status FROM staattendance WHERE Date='" + date+ "'");
            ResultSet rs = pst.executeQuery();
            tblStaff.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_StaDateActionPerformed

    private void StaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaIDActionPerformed
       
      try {
            String eid = txtStaID.getText();
            if (eid.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Enter Staff Id !!!");
                return;
            }

            PreparedStatement pst = db.getpst("SELECT * FROM staattendance WHERE EID='" + eid + "'");
            ResultSet rs = pst.executeQuery();
            tblStaff.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_StaIDActionPerformed

    private void StuRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuRefreshActionPerformed
        txtSID.setText(null);
        jDateChooser1.setDate(null);
        showtable();
        
    }//GEN-LAST:event_StuRefreshActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
       Main M= new Main("Welcome Admin");
       M.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Stu_AttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stu_AttActionPerformed
       Stu_Attendance sadd = new Stu_Attendance();
       sadd.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Stu_AttActionPerformed

    private void StuRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuRefresh1ActionPerformed
         txtStaID.setText(null);
        jDateChooser2.setDate(null);
        showtable1();
    }//GEN-LAST:event_StuRefresh1ActionPerformed

    private void SatBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatBackActionPerformed
       Main M= new Main("Welcome Admin");
       M.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_SatBackActionPerformed

    private void StaAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaAttActionPerformed
       StaffAtt add = new StaffAtt();
       add.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_StaAttActionPerformed

    private void StaAtt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaAtt1ActionPerformed
        Salary add = new Salary();
       add.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_StaAtt1ActionPerformed

    private void StaAtt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaAtt2ActionPerformed
        StaffOut SO = new StaffOut();
        SO.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StaAtt2ActionPerformed

    private void Pai_StuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pai_StuActionPerformed
        try
        {
         
        DefaultPieDataset ps = new DefaultPieDataset();
        ResultSet rs=db.getResultSet ("Select count(Status) from stuattendance Where SID='"
                +txtSID.getText()+"' AND Status='Present'");
         if(rs.next()==true)
                {
                String count=db.rs.getString("count(Status)");
		System.out.println(count);
                double per = (Integer.parseInt(count)*20)/100;
                System.out.println(count);
                ps.setValue("Present\nPer: "+per+"%\nDays: "+count+"", new Integer(count));
                }
        ResultSet rs1=db.getResultSet ("Select count(Status) from stuattendance Where SID='"
                +txtSID.getText()+"' AND Status='Absence'");
        if(rs1.next()==true)
                {
                String count=db.rs.getString("count(Status)");
		System.out.println(count);
                double per = (Integer.parseInt(count)*20)/100;
                System.out.println(count);
                ps.setValue("Absence\nPer: "+per+"%\nDays: "+count+"", new Integer(count));
                }
         ResultSet rs2=db.getResultSet ("Select count(Status) from stuattendance Where SID='"
                 +txtSID.getText()+"' AND Status='Late Comer'");
         if(rs2.next()==true)
                {
                String count=db.rs.getString("count(Status)");
		System.out.println(count);
                double per = (Integer.parseInt(count)*20)/100;
                System.out.println(count);
                ps.setValue("Late Comer\nPer: "+per+"%\nDays: "+count+"", new Integer(count));
                }
    
JFreeChart chart = ChartFactory.createPieChart("Student Attendance Performance", ps, true, true, true);
PiePlot p=(PiePlot)chart.getPlot();
ChartFrame frame = new ChartFrame("Pie Chart",chart);
frame.setVisible(true);
frame.setSize(450,500);
frame.setAlwaysOnTop(true); 

                }

        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_Pai_StuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //Desktop.getDesktop().open(new File("C:\\Users\\lynx\\Desktop\\Kamila\\UnAuthorized"));
            Desktop.getDesktop().open(new File("C:\\Users\\HOME\\Desktop\\Kamila\\UnAuthorized"));

        } catch (IOException ex) {
            
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void StaDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaDate1ActionPerformed
          try {
            String eid = txtStaID1.getText();
            if (eid.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Enter Time !!!");
                return;
            }

            PreparedStatement pst = db.getpst("SELECT * FROM staattendance WHERE Date='" + eid + "'");
            ResultSet rs = pst.executeQuery();
            untbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_StaDate1ActionPerformed

    private void StaID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaID1ActionPerformed
         try {
            String eid = txtStaID1.getText();
            if (eid.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Enter Time !!!");
                return;
            }

            PreparedStatement pst = db.getpst("SELECT * FROM staattendance WHERE Time='" + eid + "'");
            ResultSet rs = pst.executeQuery();
            untbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_StaID1ActionPerformed

    private void StuRefresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuRefresh2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StuRefresh2ActionPerformed

    private void SatBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatBack1ActionPerformed
         Main M= new Main("Welcome Admin");
       M.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_SatBack1ActionPerformed

    private void PaiSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaiSatActionPerformed
         try
        {
         
        DefaultPieDataset ps = new DefaultPieDataset();
        ResultSet rs=db.getResultSet ("Select count(Status) from staattendance Where EID='"+txtStaID.getText()+"' AND (Status='Present'||Status='Present with OT')");
         if(rs.next()==true)
                {
                String count=db.rs.getString("count(Status)");
		System.out.println(count);
                double per = (Integer.parseInt(count)*20)/100;
                System.out.println(count);
                ps.setValue("Present\nPer: "+per+"%\nDays: "+count+"", new Integer(count));
                }
        ResultSet rs1=db.getResultSet ("Select count(Status) from staattendance Where EID='"+txtStaID.getText()+"' AND Status='Absence'");
        if(rs1.next()==true)
                {
                String count=db.rs.getString("count(Status)");
		System.out.println(count);
                double per = (Integer.parseInt(count)*20)/100;
                System.out.println(count);
                ps.setValue("Absence\nPer: "+per+"%\nDays: "+count+"", new Integer(count));
                }
         ResultSet rs2=db.getResultSet ("staattendance Where EID='"+txtStaID.getText()+"' AND (Status='Half Day'||Status='Short Leave')");
         if(rs2.next()==true)
                {
                String count=db.rs.getString("count(Status)");
		System.out.println(count);
                double per = (Integer.parseInt(count)*20)/100;
                System.out.println(count);
                ps.setValue("Short Leave\nPer: "+per+"%\nDays: "+count+"", new Integer(count));
                }
    
JFreeChart chart = ChartFactory.createPieChart("Student Attendance Performance", ps, true, true, true);
PiePlot p=(PiePlot)chart.getPlot();
ChartFrame frame = new ChartFrame("Pie Chart",chart);
frame.setVisible(true);
frame.setSize(450,500);
                }

        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_PaiSatActionPerformed

    private void tblStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStuMouseClicked
        ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel)tblStu.getModel();
        int selectedRowIndex = tblStu.getSelectedRow();
        try
        {
            txtSID.setText(model.getValueAt(selectedRowIndex, 2).toString());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date1=sdf.parse(model.getValueAt(selectedRowIndex, 1).toString());
            jDateChooser1.setDate(date1);
            
      
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_tblStuMouseClicked

    private void tblStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStaffMouseClicked
        ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel)tblStaff.getModel();
        int selectedRowIndex = tblStaff.getSelectedRow();
        try
        {
            txtStaID.setText(model.getValueAt(selectedRowIndex, 2).toString());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date1=sdf.parse(model.getValueAt(selectedRowIndex, 1).toString());
            jDateChooser2.setDate(date1);
            
      
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_tblStaffMouseClicked

    private void untblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_untblMouseClicked
            ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel)untbl.getModel();
        int selectedRowIndex = untbl.getSelectedRow();
        try
        {
            txtStaID1.setText(model.getValueAt(selectedRowIndex, 2).toString());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date1=sdf.parse(model.getValueAt(selectedRowIndex, 1).toString());
            jDateChooser3.setDate(date1);
            
      
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_untblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton PaiSat;
    private javax.swing.JButton Pai_Stu;
    private javax.swing.JButton SatBack;
    private javax.swing.JButton SatBack1;
    private javax.swing.JButton StaAtt;
    private javax.swing.JButton StaAtt1;
    private javax.swing.JButton StaAtt2;
    private javax.swing.JButton StaDate;
    private javax.swing.JButton StaDate1;
    private javax.swing.JButton StaID;
    private javax.swing.JButton StaID1;
    private javax.swing.JPanel Staff;
    private javax.swing.JButton StuDate;
    private javax.swing.JButton StuID;
    private javax.swing.JButton StuRefresh;
    private javax.swing.JButton StuRefresh1;
    private javax.swing.JButton StuRefresh2;
    private javax.swing.JButton Stu_Att;
    private javax.swing.JPanel Student;
    private javax.swing.JPanel Unknown;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTable tblStu;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtStaID;
    private javax.swing.JTextField txtStaID1;
    private javax.swing.JTable untbl;
    // End of variables declaration//GEN-END:variables

  public void showtable()
    {
        try{
            PreparedStatement pst= db.getpst("SELECT * FROM stuattendance");
            ResultSet rs = pst.executeQuery();
            tblStu.setModel(DbUtils.resultSetToTableModel(rs));    
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
  
public void showtable1()
    {
        try{
           
            PreparedStatement pst = db.getpst("SELECT * FROM staattendance");
            ResultSet rs = pst.executeQuery();
            tblStaff.setModel(DbUtils.resultSetToTableModel(rs));
              }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

public void showtable3()
    {
        try{
           
            PreparedStatement pst = db.getpst("SELECT * FROM unauthorized");
            ResultSet rs = pst.executeQuery();
            untbl.setModel(DbUtils.resultSetToTableModel(rs));
              }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

}
