/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package face_rec;

/**
 *
 * @author Dansugan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main(String name) {
        
        setTitle("Admin Page");
        setResizable(false);
        setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        initComponents();
        lbl_user.setText(name);
    }

    private Main() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonlout = new javax.swing.JButton();
        lbl_user = new javax.swing.JLabel();
        jButtonStaff = new javax.swing.JButton();
        jButtonStaffAdd = new javax.swing.JButton();
        jButtonStudent = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonlout.setBackground(new java.awt.Color(204, 204, 255));
        jButtonlout.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonlout.setText("Log Out");
        jButtonlout.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonlout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonlout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloutActionPerformed(evt);
            }
        });

        lbl_user.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(153, 102, 255));
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red));
        lbl_user.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonStaff.setBackground(new java.awt.Color(204, 204, 255));
        jButtonStaff.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButtonStaff.setText("Staff Details");
        jButtonStaff.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaffActionPerformed(evt);
            }
        });

        jButtonStaffAdd.setBackground(new java.awt.Color(204, 204, 255));
        jButtonStaffAdd.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButtonStaffAdd.setText("Attendance Process");
        jButtonStaffAdd.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonStaffAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStaffAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaffAddActionPerformed(evt);
            }
        });

        jButtonStudent.setBackground(new java.awt.Color(204, 204, 255));
        jButtonStudent.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButtonStudent.setText("Student Details");
        jButtonStudent.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4174767-beautiful-background-images.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButtonStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButtonStaffAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jButtonlout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButtonStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jButtonStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonStaffAdd))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonlout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButtonStudent))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonloutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloutActionPerformed
        Welcome_page lgn = new Welcome_page();
        lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonloutActionPerformed

    private void jButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaffActionPerformed
         Staff stf = new Staff();
        stf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonStaffActionPerformed

    private void jButtonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentActionPerformed
         Student std = new Student();
        std.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonStudentActionPerformed

    private void jButtonStaffAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaffAddActionPerformed
       Attendance add = new Attendance();
       add.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_jButtonStaffAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStaff;
    private javax.swing.JButton jButtonStaffAdd;
    private javax.swing.JButton jButtonStudent;
    private javax.swing.JButton jButtonlout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_user;
    // End of variables declaration//GEN-END:variables
}
