/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package face_rec;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Dansugan
 */
public class Student extends javax.swing.JFrame {
    
     DB db = new DB();
     String s;
    
    public Student() {
        setTitle("Student Page");
        setResizable(false);
        setLocationRelativeTo(null);
        initComponents();
        showtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPNo = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        BtnReg = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        jTextFieldST = new javax.swing.JTextField();
        jTextFieldOT = new javax.swing.JTextField();
        date_chooser = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSSID = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableStdnt = new javax.swing.JTable();
        BtnRemv = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnCImage = new javax.swing.JButton();
        lbl_image = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BtnCF = new javax.swing.JButton();
        BtnCls = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Personal Data");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Date Of Birth");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Start Time");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Course");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Email ID");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Over Time");

        jTextFieldName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTextFieldPNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Bio Medical", "Business Management", "Engineering" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        BtnReg.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BtnReg.setText("Register");
        BtnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegActionPerformed(evt);
            }
        });

        BtnUpdate.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BtnUpdate.setText("Update");
        BtnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        jTextFieldST.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTextFieldOT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        date_chooser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 159, Short.MAX_VALUE)
                            .addComponent(jTextFieldPNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(date_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldST)
                            .addComponent(jTextFieldOT))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(date_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldST, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextFieldOT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldPNo)))
                .addGap(18, 18, 18)
                .addComponent(BtnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldSSID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSSID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSSID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSSIDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldSSIDMouseEntered(evt);
            }
        });
        jTextFieldSSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSSIDActionPerformed(evt);
            }
        });
        jTextFieldSSID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSSIDKeyPressed(evt);
            }
        });

        jTableStdnt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableStdnt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTableStdnt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableStdnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStdntMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableStdnt);

        BtnRemv.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BtnRemv.setText("Remove");
        BtnRemv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemvActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("SID");

        BtnCImage.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BtnCImage.setText("Choose Image");
        BtnCImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCImageMouseClicked(evt);
            }
        });
        BtnCImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCImageActionPerformed(evt);
            }
        });

        lbl_image.setText(" ");
        lbl_image.setToolTipText("");
        lbl_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_blue_repeat.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(BtnCImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRemv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSSID, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSSID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRemv)
                    .addComponent(BtnCImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BtnCF.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BtnCF.setText("Capture Face");
        BtnCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCFActionPerformed(evt);
            }
        });

        BtnCls.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BtnCls.setText("Exit");
        BtnCls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(BtnCF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(480, 480, 480)
                .addComponent(BtnCls, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCF)
                    .addComponent(BtnCls)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegActionPerformed
        
         try
         {
             
             
             
            PreparedStatement pst= db.getpst("INSERT INTO student(Name, DOB, Course, Start_Time, "
                    + "Over_Time, EmailID,images) VALUES (?,?,?,?,?,?,?)");
            InputStream is = new FileInputStream(new File(s));
           
            pst.setString(1,jTextFieldName.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date=sdf.format(date_chooser.getDate());
            pst.setString(2, date);
            //pst.setString(2,jTextFieldDOB.getText());
            String course=jComboBox1.getSelectedItem().toString();
            pst.setString(3,course);
            pst.setString(4,jTextFieldST.getText());
            pst.setString(5,jTextFieldOT.getText());
            pst.setString(6,jTextFieldPNo.getText());
            pst.setBlob(7,is);
           
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data of " +jTextFieldName.getText()+" Successfully Registered");
            cleartxt();
            showtable();
         }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    
    }//GEN-LAST:event_BtnRegActionPerformed

    private void BtnRemvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemvActionPerformed
        
         try
         {
            PreparedStatement pst= db.getpst("DELETE FROM student WHERE SID=?");
            pst.setString(1,jTextFieldSSID.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data of " +jTextFieldSSID.getText()+" Successfully Deleted");
            cleartxt();
            showtable();
         }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_BtnRemvActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try{
            InputStream is = new FileInputStream(new File(s));
            int row = jTableStdnt.getSelectedRow();
            String value = (jTableStdnt.getModel().getValueAt(row, 0).toString());
            String query="UPDATE student SET Name=?,DOB=?,Course=?,Start_Time=?,Over_Time=?,EmailID=?,"
                    + "images=? WHERE SID="+ value;

	    PreparedStatement pst= db.getpst(query);
            pst.setString(1,jTextFieldName.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date=sdf.format(date_chooser.getDate());
            pst.setString(2, date);
            
            String course=jComboBox1.getSelectedItem().toString();
            pst.setString(3,course);
            pst.setString(4,jTextFieldST.getText());
            pst.setString(5,jTextFieldOT.getText());
            pst.setString(6,jTextFieldPNo.getText());
            pst.setBlob(7,is);
            
            pst.executeUpdate();
			
	    DefaultTableModel model= (DefaultTableModel)jTableStdnt.getModel();
	    model.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Data of " +jTextFieldName.getText()+" Updated");
            cleartxt();
            showtable();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);}     
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnClsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClsActionPerformed
        Main M= new Main("Welcome Admin");
        M.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnClsActionPerformed
 
    private void BtnCImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCImageActionPerformed
             
         JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             lbl_image.setIcon(ResizeImage(path));
             s = path;
            }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }   
    }//GEN-LAST:event_BtnCImageActionPerformed

    private void BtnCImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCImageMouseClicked

    private void jTableStdntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStdntMouseClicked
        
        ResultSet rs = null;
        DefaultTableModel model = (DefaultTableModel)jTableStdnt.getModel();
        int selectedRowIndex = jTableStdnt.getSelectedRow();
        try
        {
            jTextFieldSSID.setText(model.getValueAt(selectedRowIndex, 0).toString());
            jTextFieldName.setText(model.getValueAt(selectedRowIndex, 1).toString());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date1=sdf.parse(model.getValueAt(selectedRowIndex, 2).toString());
            date_chooser.setDate(date1);
            jComboBox1.setSelectedItem(model.getValueAt(selectedRowIndex, 3).toString());
            jTextFieldST.setText(model.getValueAt(selectedRowIndex, 4).toString());
            jTextFieldOT.setText(model.getValueAt(selectedRowIndex, 5).toString());
            jTextFieldPNo.setText(model.getValueAt(selectedRowIndex, 6).toString());
            
      
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jTableStdntMouseClicked

    private void BtnCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCFActionPerformed

        try{
        
        int id = Integer.parseInt(jTextFieldSSID.getText().replace("SID: ", ""));
        String Sname = jTextFieldName.getText();
        String Scourse = jComboBox1.getSelectedItem().toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(date_chooser.getDate());
        String dob= date;
        String st= jTextFieldST.getText();
        String ot= jTextFieldOT.getText();
        String mail = jTextFieldPNo.getText();
        String images=lbl_image.getText(); 
        
        Capture C= new Capture(id, Sname, Scourse,dob, st, ot, mail,images);
        C.setVisible(true);
        
       cleartxt();
       showtable();
       }
       catch(Exception ex)
       {
           System.out.println(ex);
       }
    }//GEN-LAST:event_BtnCFActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
  
            String course=jComboBox1.getSelectedItem().toString();
            if(course =="Software Engineering")
            {
                jTextFieldST.setText("13:00:00");
                jTextFieldOT.setText("17:30:00");
            } else if(course =="Bio Medical")
            {
                jTextFieldST.setText("09:00:00");
                jTextFieldOT.setText("17:30:00");
            } else if(course =="Business Management")
            {
                jTextFieldST.setText("09:00:00");
                jTextFieldOT.setText("13:00:00");
            } else
            {
                jTextFieldST.setText("10:30:00");
                jTextFieldOT.setText("16:30:00");
            }
          
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldSSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSSIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showtable();
        cleartxt();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldSSIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSSIDMouseEntered
    
    }//GEN-LAST:event_jTextFieldSSIDMouseEntered

    private void jTextFieldSSIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSSIDMouseClicked
     
        
    }//GEN-LAST:event_jTextFieldSSIDMouseClicked

    private void jTextFieldSSIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSSIDKeyPressed
         try {
            String sid = jTextFieldSSID.getText();
            if (sid.equals("")) {
                
                return;
            }

            PreparedStatement pst = db.getpst("SELECT * FROM Student WHERE SID='" 
                    + jTextFieldSSID.getText() + "'");
            ResultSet rs = pst.executeQuery();
            jTableStdnt.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextFieldSSIDKeyPressed

    public void showtable()
    {
        try{
            PreparedStatement pst= db.getpst("SELECT * FROM student");
            ResultSet rs = pst.executeQuery();
            jTableStdnt.setModel(DbUtils.resultSetToTableModel(rs));    
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
     private void cleartxt()
     {
         jTextFieldName.setText(null);
         date_chooser.setDate(null);
         jTextFieldST.setText(null);
         jTextFieldOT.setText(null);
         jTextFieldPNo.setText(null);
         jTextFieldSSID.setText(null);
         lbl_image.setIcon(null);  
     }
     
    public ImageIcon ResizeImage(String imgPath)
	{
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCF;
    private javax.swing.JButton BtnCImage;
    private javax.swing.JButton BtnCls;
    private javax.swing.JButton BtnReg;
    private javax.swing.JButton BtnRemv;
    private javax.swing.JButton BtnUpdate;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableStdnt;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldOT;
    private javax.swing.JTextField jTextFieldPNo;
    private javax.swing.JTextField jTextFieldSSID;
    private javax.swing.JTextField jTextFieldST;
    private javax.swing.JLabel lbl_image;
    // End of variables declaration//GEN-END:variables

}
