/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package face_rec;

import java.sql.*;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.chart.PieChart;



/**
 *
 * @author HOME
 */
public class welcomepage extends javax.swing.JFrame {
DB db = new DB();
String dateText = "";
private PieChart p;




    /**
     * Creates new form welcomepage
     */
    public welcomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        date_chooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addGap(70, 70, 70))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(jButton7))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(0, 30, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton5)
                        .addGap(13, 13, 13)
                        .addComponent(jButton4)
                        .addGap(13, 13, 13)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        /*Login C= new Login();
         C.setVisible(true);
         this.dispose();*/
         
         
           try {
            
            //ResultSet resultSet = db.stmt.executeQuery("SELECT `SID` FROM `stuattendance` WHERE (Status='Absence' OR Status='Late Comer')");
           
 
  //ResultSet rs=db.stmt.executeQuery("SELECT `SID` FROM `stuattendance` WHERE (Status='Absence' OR Status='Late Comer')");
  String AB= "Absence";

  String SQL= "(SELECT `SID` FROM `student`)";
  db.getResultSet(SQL);
  db.stmt.executeQuery(SQL);
  ResultSetMetaData rsmd=db.getResultSet(SQL).getMetaData();
  
  int colCount=rsmd.getColumnCount();
  int idArray[];
  idArray = new int [colCount];
  //int size= idArray.length;
  
  for(int a=1; a<=colCount; a++)
  {
      int id=Integer.valueOf(db.rs.getString(a));
      System.out.println(id);
      try{
        /*ResultSet rs=db.getResultSet("select * from stuattendance WHERE SID='"
                    +id+"' AND Date='now()'");
        
        while(db.rs.next())
        {
            if(rs.next()==true)
                {
                    System.out.println("Already attendance marked");
                }
            
            else{*/
               
                PreparedStatement pst= db.getpst("INSERT INTO stuattendance "
                        + "(Date, SID, Time, Status) VALUES (?,?,?,?)");
                    
                pst.setString(1,"2019/08/29");
                pst.setString(2,String.valueOf(id));
                pst.setString(3,"09:00:00");
                pst.setString(4,AB);
        
                    
               pst.executeUpdate();
               
               
          //  }
        //}
      }catch(Exception e)
      {
          System.out.println(e);
      }
  }
  

  } catch (SQLException ex) { 
        System.out.println(ex);
    } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    try{
        String SQL= "(SELECT `SID` FROM `student`)";
		  db.getResultSet(SQL);
		  db.stmt.executeQuery(SQL);
		  ResultSetMetaData rsmd=db.getResultSet(SQL).getMetaData();
		  int colCount=rsmd.getColumnCount();

  while(db.rs.next())
  {
      int a =1;
      
	  for(int i=1; i<=colCount;i++)
	  {
            
	       System.out.println(db.rs.getString(i)+"\t\t");
                
               //jTextField1.setText(String.valueOf(db.rs.getString(i)));
          
               PreparedStatement pst= db.getpst("INSERT INTO stuattendance (Date, SID, Time, Status)  VALUES (?,?,?,?)");
                    
                pst.setString(1,"2019/08/29");
                pst.setString(2,String.valueOf(db.rs.getString(i)));
                pst.setString(3,"09:00:00");
                pst.setString(4,"AB");
          
                pst.executeUpdate();
                
                //jTextField1.setText("");
             
            }
                
	  
	  System.out.println();
  } 
    }catch(Exception ex)
    {
        
    }

  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          
        try{
        String SQL= "(SELECT `SID` FROM `student`)";
		  db.getResultSet(SQL);
		  db.stmt.executeQuery(SQL);
		  ResultSetMetaData rsmd=db.getResultSet(SQL).getMetaData();
		  int colCount=rsmd.getColumnCount();

  while(db.rs.next())
  {
      int a =1;
      
	  for(int i=1; i<=colCount;i++)
	  {
            
	       System.out.println(db.rs.getString(i)+"\t\t");
                
               //jTextField1.setText(String.valueOf(db.rs.getString(i)));
          
               PreparedStatement pst= db.getpst("INSERT INTO stuattendance (Date, SID, Time, Status)  VALUES (?,?,?,?)");
                    
                pst.setString(1,"2019/08/29");
                pst.setString(2,String.valueOf(db.rs.getString(i)));
                pst.setString(3,"09:00:00");
                pst.setString(4,"AB");
          
                pst.executeUpdate();
                
                //jTextField1.setText("");
                String to="kamila.gnanam@gmail.com";
                String sub = "Student Absence Notification";
				String msg = "Dear Parent, \r\n\r\nWe are pleased to inform you that today your child absence for the class,\r\nSo please consider as an important note";
				Email e = new Email(to,sub,msg);
				e.setVisible(true);
                               e.dispose();
            }
                
	  
	  System.out.println();
  } 
    }catch(Exception ex)
    {
        
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
        String SQL= "(SELECT `EID` FROM `staattendance` WHERE Status='Absence' AND Date='2019/08/31')";
	db.getResultSet(SQL);
	db.stmt.executeQuery(SQL);
	ResultSetMetaData rsmd=db.getResultSet(SQL).getMetaData();
	int colCount=rsmd.getColumnCount();

  while(db.rs.next())
  {
	  for(int i=1; i<=colCount;i++)
	  {
           
               
                ResultSet rs2=db.getResultSet ("Select MID from staff Where EID='"+db.rs.getString(i)+"'");
                   if(rs2.next()==true)
                   {
                        String email=db.rs.getString("MID");
                        String to=email;
                        String sub = "Student Late Commer Notification";
			String msg = "Dear Parent, \r\n\r\nWe are pleased to inform you that today your child came late to the class,\r\nSo consider as a late commer today";
			Email e = new Email(to,sub,msg);
			e.setVisible(false);
                        e.dispose(); 
                   }
                
            
               
	  System.out.println();
          }
  } 
    }catch(Exception ex)
    {
        
    }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          
        try{
        String SQL= "(SELECT `SID` FROM `student`)";
		  db.getResultSet(SQL);
		  db.stmt.executeQuery(SQL);
		  ResultSetMetaData rsmd=db.getResultSet(SQL).getMetaData();
		  int colCount=rsmd.getColumnCount();
                System.out.println("done");  
            while(db.rs.next())
  {      
                   ResultSet rs1=db.getResultSet("select * from stuattendance WHERE SID=1 AND Date=2019/09/02");
             System.out.println("done");  
            if(rs1.next()==true)
                {
                    System.out.println("Already attendance marked");
                }
            
            else{

   System.out.println("done");  
      int a =1;
      
	  for(int i=1; i<=colCount;i++)
	  {
            
	       System.out.println(db.rs.getString(i)+"\t\t");
                
               //jTextField1.setText(String.valueOf(db.rs.getString(i)));
         
               PreparedStatement pst= db.getpst("INSERT INTO stuattendance (Date, SID, Time, Status) "
                       + " VALUES (?,?,?,?)");
                    
                pst.setString(1,"2019/09/02");
                pst.setString(2,String.valueOf(db.rs.getString(i)));
                pst.setString(3,"09:00:00");
                pst.setString(4,"AB");
          
                pst.executeUpdate();
                
                //jTextField1.setText("");
                String to="kamila.gnanam@gmail.com";
                String sub = "Student Absence Notification";
				String msg = "Dear Parent, We are pleased to inform "
                                        + "you that today your child absence for the class,"
                                        + "So please consider as an important note";
				Email e = new Email(to,sub,msg);
				e.setVisible(true);
                               e.dispose();
            }
                
	  
	  System.out.println();
  
    }}
  }catch(Exception ex){}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
        String SQL= "(SELECT `SID` FROM `student`)";
		  db.getResultSet(SQL);
		  db.stmt.executeQuery(SQL);
		ResultSetMetaData rsmd=db.getResultSet(SQL).getMetaData();
		  int colCount=rsmd.getColumnCount();

  while(db.rs.next())
  {
      int a =1;
      
	  for(int i=1; i<=colCount;i++)
	  {
            ResultSet rs1=db.getResultSet("select * from stuattendance WHERE SID='"
                    +String.valueOf(db.rs.getString(i))+"' AND Date='2010/2/9'");
            
            if(rs1.next()==true)
                {
                    System.out.println("Already attendance marked");
                }
            
            else{
	       System.out.println(db.rs.getString(i)+"\t\t");
               
               PreparedStatement pst= db.getpst("INSERT INTO stuattendance (Date, SID, Time, Status)  VALUES (?,?,?,?)");
                    
                pst.setString(1,"2010/2/9");
                pst.setString(2,String.valueOf(db.rs.getString(i)));
                pst.setString(3,"09:00:00");
                pst.setString(4,"AB");
          
                pst.executeUpdate();
                
                
            }
                
	  
	  System.out.println();
  } 
 }}catch(Exception ex)
    {
        
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       try {
        
            String SQL= "(SELECT `SID` FROM `stuattendance` where Status='Absence')";
		  db.getResultSet(SQL);
		  db.stmt.executeQuery(SQL);
		ResultSetMetaData rsmd=db.getResultSet(SQL).getMetaData();
		  int colCount=rsmd.getColumnCount();
       
   
      
     while(db.rs.next())
     {
	//ResultSetMetaData rsmd=db.getResultSet(SQL).getMetaData();
        
	//int colCount=rsmd.getColumnCount();
        
        //double per = (colCount*20)/100;
         System.out.println(db.stmt);
         System.out.println(colCount);
     }
         } catch (SQLException ex) {
        Logger.getLogger(welcomepage.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      
    try {
       ResultSet rs=db.getResultSet ("Select count(SID) from student");
         if(rs.next()==true)
                {
                String count=db.rs.getString("count(Status)");
		System.out.println(count);
                int cont = Integer.parseInt(count);
                
                int countArr[];
                countArr = new int[cont];
                
                for(int i=0; i<countArr.length; i++)
                {
                    ResultSet rs1=db.getResultSet ("Select SID from student");
                    if(rs1.next()==true){
                        
                    ResultSet rs2=db.getResultSet ("select * from stuattendance WHERE SID='"
                    +rs1.getString(i)+"'");
                    
                    if(rs2.next()==true){
                        System.out.println("Already attendance marked");
                    }
                    else
                    {
                         PreparedStatement pst= db.getpst("INSERT INTO stuattendance "
                        + "(Date, SID, Time, Status) VALUES (?,?,?,?)");
                    
                pst.setString(1,"2019/09/09");
                pst.setString(2,rs1.getString(i));
                pst.setString(3,"09:00:00");
                pst.setString(4,"Absence");
                    }
                    }
                }
                
                }
    } catch (SQLException ex) {
        Logger.getLogger(welcomepage.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

public void AB()
{
     try{
        String SQL= "(SELECT `SID` FROM `student`)";
		  db.getResultSet(SQL);
		  db.stmt.executeQuery(SQL);
		  ResultSetMetaData rsmd=db.getResultSet(SQL).getMetaData();
		  int colCount=rsmd.getColumnCount();

  while(db.rs.next())
  {
	  for(int i=1; i<=colCount;i++)
	  {
	       System.out.println(db.rs.getString(i)+"\t\t");
              
            PreparedStatement pst= db.getpst("INSERT INTO stuattendance (Date, SID, Time, Status)"
                    + "VALUES (?,?,?,?)");
               pst.setString(1,"2019/08/29");
               pst.setString(2,String.valueOf(db.rs.getString(i)));
               pst.setString(3,"09:00:00");
               pst.setString(4,"AB");
               pst.executeUpdate();
                
               ResultSet rs2=db.getResultSet ("Select MID from staff Where EID='"+db.rs.getString(i)+"'");
                   if(rs2.next()==true)
                   {
                        String email=db.rs.getString("MID");
                        String to=email;
                        String sub = "Student Late Commer Notification";
			String msg = "Dear Parent, We are pleased to inform you that today your "
                                + "child didn't attendent to the lectures/class, So today their "
                                + "attendance consider as a "
                                + "ABSENCE today";
			Email e = new Email(to,sub,msg);
			e.setVisible(false);
                        e.dispose(); 
                   }
            }
	  System.out.println();
  } 
    }catch(Exception ex)
    {
        
    }
}
}
